name: "CI Build"

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  UPSTREAM_REPO: https://github.com/DecentSoftware-eu/DecentHolograms
  BRANCH: main
  MAX_COMMITS: 10

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.check.outputs.continue }}
      sha: ${{ steps.upstream.outputs.sha }}
      last_sha: ${{ steps.previous.outputs.last_sha }}
    steps:
      - name: Checkout CI Repo
        uses: actions/checkout@v6
      - name: Check for GitHub CLI
        run: gh --version
      - name: Get latest Upstream commit SHA
        id: upstream
        run: |
          SHA=$(git ls-remote "$UPSTREAM_REPO" "refs/heads/$BRANCH" | cut -f1)

          echo "sha=$SHA" >> $GITHUB_OUTPUT

          echo "Latest Upstream SHA: $SHA"
      - name: Get previous Upstream SHA
        id: previous
        run: |
          LAST_SHA=$(cat .last_upstream_sha 2>/dev/null || true)
          echo "last_sha=$LAST_SHA" >> "$GITHUB_OUTPUT"

          echo "Previous SHA: ${LAST_SHA:-none}"
      - name: Stop if nothing changed
        id: check
        run: |
          if [[ "${{ steps.upstream.outputs.sha }}" = "${{ steps.previous.outputs.last_sha }}" ]]; then
            echo "No upstream changes found."
            echo "continue=false" >> $GITHUB_OUTPUT
          else
            echo "continue=true" >> $GITHUB_OUTPUT
          fi
  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.continue }} == "true"
    steps:
      - name: Clone upstream repository
        run: git clone --branch "$BRANCH" "$UPSTREAM_REPO" upstream
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Make Gradle exectuable
        working-directory: upstream
        run: chmod +x gradlew
      - name: Build Jar
        working-directory: upstream
        run: ./gradlew shadowJar -x test
      - name: Find build artifacts
        id: artifact
        run: |
          FILE=$(find upstream/plugin/build/libs \
            -maxdepth 1 \
            -type f \
            \( -name "DecentHolograms*.jar" -o -name "*.war" \) \
            ! -name "*-sources.jar" \
            ! -name "*-javadoc.jar" \
            | head -n 1)

          if [ -z "$FILE" ]; then
            echo "No Build artifact found!"
            exit 1
          fi

          echo "file=$FILE" >> $GITHUB_OUTPUT

          echo "Build Artifact: $FILE"
      - name: Determine next build number
        id: version
        shell: bash
        run: |
          LAST=$(cat .last_build_number 2>/dev/null || echo 0)
          NEXT=$((LAST + 1))

          echo "last=$LAST" >> "$GITHUB_OUTPUT"
          echo "next=$NEXT" >> "$GITHUB_OUTPUT"

          echo "Previous build number: ${LAST:-none}"
          echo "Next build number: $NEXT"
      - name: Generate Changelog
        id: changelog
        shell: bash
        working-directory: upstream
        run: |
          set -eo pipefail
          
          OLD_SHA="${{ needs.check.outputs.last_sha }}"
          NEW_SHA="${{ needs.check.outputs.sha }}"

          if [[ -z "$OLD_SHA" ]]; then
            echo "First build!"

            TOTAL=$(git rev-list --count HEAD)

            LOG=$(git log \
              -n "$MAX_COMMITS" \
              --pretty=format:'- [\`%h\`](${UPSTREAM_REPO}/commit/%H) %s - %an')
          else
            TOTAL=$(git rev-list --count "${OLD_SHA}..${NEW_SHA}")
            
            LOG=$(git log \
              "${OLD_SHA}..${NEW_SHA}" \
              -n "$MAX_COMMITS" \
              --pretty=format:'- [\`%h\`](${UPSTREAM_REPO}/commit/%H) %s - %an')
          fi

          if [[ "$TOTAL" -gt "$MAX_COMMITS" ]]; then
            OMITTED=$((TOTAL - MAX_COMMITS))
            LOG="${LOG}"$'\n'"- ...and ${OMITTED} more."
          fi

          echo "Generated Changelog:"
          echo "$LOG"

          printf 'logs<<EOF\n%s\nEOF\n' "$LOG" >> $GITHUB_OUTPUT
      - name: Create release
        if: steps.check.outputs.continue == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat > release_notes.txt << EOF
          Automated Upstream Build

          ## Changes

          ${{ steps.changelog.outputs.logs }}
          EOF

          gh release create "${{ steps.version.outputs.next }}" \
            "${{ steps.artifact.outputs.file }}" \
            --title "Build ${{ steps.version.outputs.next }}" \
            --notes-file release_notes.txt
      - name: "Update Upstream SHA and last build number"
        if: steps.check.outputs.continue == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ steps.upstream.outputs.sha }}" > .last_upstream_sha
          echo "${{ steps.version.outputs.next }}" > .last_build_number

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .last_upstream_sha .last_build_number
          git commit -m "Update upstream SHA and last build number file" || exit 0
          git push
